#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
  path: /
  controller: App\Controller\HomepageController::index

create_ticket:
  path: /ticket/create
  controller: App\Controller\TicketController::create

update_ticket:
  path: /ticket/{id}/update
  controller: App\Controller\TicketController::update